# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Kwiki-Edit-BackgroundSave
version:      0.02
version_from: lib/Kwiki/Edit/BackgroundSave.pm
installdirs:  site
requires:
    JSON:                          0
    Kwiki::Prototype:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
